### PR TITLE
Workaround for lib issue (https://github.com/mesos/elasticsearch/issu…

### PR DESCRIPTION
**Pull request by brndnmtthws**
…es/422).

cc @frankscholten

### CODE REVIEW

**Comment by containersol** [comment]
Can one of the admins verify this patch?

**Comment by philwinder** [comment]
Can you explain what this is doing? We already set the environment variable in:
https://github.com/mesos/elasticsearch/blob/master/scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/configuration/ExecutorEnvironmentalVariables.java#L48
Which defaults to `/usr/lib/libmesos.so`, which is the same as yours. So I am confused as to what isn't working and what you are trying to achieve.

Remember that this path is _inside_ the container.

Thanks for the effort though!

**Comment by brndnmtthws** [comment]
The issue is that the env var set in the environment takes precedence over the one set by Mesos (through the ES scheduler). I had the same issue with Storm, and fixed it this way: https://github.com/mesos/storm/blob/dfbebd8f495e7dfd600a623c0b858a3558259ea4/src/main/storm/mesos/MesosNimbus.java#L806

**Comment by philwinder** [comment]
Ah really?! Ok thanks.

**Comment by brndnmtthws** [comment]
Yeah, it's rather unfortunate.

**Pull request merged**
