### PR TITLE
WIP: upgrade framework and images to mesos 0.24.1

### PR DESCRIPTION
**Pull request by dallasmarlow**

### CODE REVIEW

**Comment by containersol** [comment]
Can one of the admins verify this patch?

**Comment by mwl** [comment]
Just tested (`./gradlew.sh clean build systemTest`) this with 14 failed tests

```
DataRetrievableAllNodesSystemTest. classMethod
DataVolumesSystemTest. testDataVolumes
DataVolumesSystemTest. testDataVolumes_differentDataDir
DiscoverySystemTest. testNodeDiscoveryRest
ExecutorSystemTest. classMethod
FrameworkRoleSystemTest. miniMesosReportsFrameworkRoleOther
FrameworkRoleSystemTest. miniMesosReportsFrameworkRoleStar
ReconciliationSystemTest. forceCheckExecutorTimeout
ReconciliationSystemTest. ifExecutorIsLostShouldStartAnother
ReconciliationSystemTest. ifExecutorIsLostWhileSchedulerIsDead
ReconciliationSystemTest. ifSchedulerLostShouldReconcileExecutors
StatusApiSystemTest. testThreeTasks
ZookeeperFrameworkSystemTest. testZookeeperFramework
ZookeeperFrameworkSystemTest. testZookeeperFramework_differentPath
```

**Comment by dallasmarlow** [comment]
@mwl our tests must have run in the master branch, i think this is a problem with mini-mesos. still investigating

**Comment by mwl** [comment]
Solved in #386. We're now on Mesos 0.25 and support Docker 1.7, 1.8 and 1.9.

**Pull request closed without merging**
