### PR TITLE
#553 Allow user request for port 0 (which will be turned into a rando…

### PR DESCRIPTION
**Pull request by ftrossbach**
…m port)

implementation and unit tests

### CODE REVIEW

**Comment by containersol** [comment]
Can one of the admins verify this patch?

**Comment by philwinder** [comment]
Hi @ftrossbach, thanks for the PR. All that should be required for your use case is an edit to the line:
```
if (configuration.getElasticsearchPorts().isEmpty()) {
```
To also include the case where the values are zero. Since ES always requires two ports, you need to select two ports. This is what the `selectTwoPortsFromRange` method is doing.

So if it's ok with you, can you just change that one line to include the "0" and "0,0" case?
Thanks, Phil

**Comment by ftrossbach** [comment]
Hi @philwinder ,

Thanks for your comment and willingness to engage on this :), but I have a question. My `selectOnePortFromRange` is used in the - maybe unlikely - case that the user specifies one port and wants the other random, e.g. "9200,0" or "0,9300". 
The "0,0" case should already be handeled by 
`if (elasticsearchPorts.isEmpty() || elasticsearchPorts.stream().allMatch(port -> port == 0))`. In the `else` case where at least one port is not 0, I map the requested ports to either themselves or to a single random port if the port is null. I also added some tests for this behaviour.

Maybe I misunderstand what you're asking?

Cheers,
Florian

**Comment by philwinder** [comment]
Ok, yes, you're right. I didn't think that anyone would ever want to do that! But since you've done it, let's stick it in. I'll run  a PR build now and post the results. Thanks!

**Comment by ftrossbach** [comment]
Great, thanks :)

**Comment by philwinder** [comment]
@ftrossbach We had a failure due to stupid PMD warning about too many methods. Can you add the line
```
@SuppressWarnings({"PMD.TooManyMethods"})
```
to the top of `TaskInfoFactoryTest.java`? Thanks.

**Comment by ftrossbach** [comment]
@philwinder done :)

**Comment by philwinder** [comment]
Passed: https://ci.infra.container-solutions.com/view/Mesos%20Elasticsearch/job/ElasticsearchPullRequests/307/console

**Pull request merged**
