### PR TITLE
Mesos labels can be added to executor tasks

### PR DESCRIPTION
**Pull request by dylanmei**
This commit enables operators to add additional meta-data to tasks launched by the ElasticSearch scheduler in the form of Mesos labels.

### CODE REVIEW

**Comment by containersol** [comment]
Can one of the admins verify this patch?

**Comment by philwinder** [comment]
@dylanmei, awesome. Thanks. This will go into the next feature release.

**Comment by dylanmei** [comment]
My pleasure. I look forward to it!

**Comment by philwinder** [comment]
CI pass:
https://ci.infra.container-solutions.com/view/Mesos%20Elasticsearch/job/ElasticsearchPullRequests/308/console

**Comment by frankscholten** [comment]
LGTM

**Pull request merged**
